name: Automatic Copying of HTML-Files

on:
  workflow_dispatch:
  push:
    paths:
      - 'sphinx_docs/_build/html/**'

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files
        run: |
          mkdir -p docs
          cp -ru sphinx_docs/_build/html/* docs
          
      - name: Commit and push if it changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatic Copying of HTML-Files"
          git push
