name: Automatisches Loeschen von Example Daten

on:
  push:
    paths:
      - 'Examples/**'
  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cleanup files
        run: |
          # Change to the Examples directory
          cd Examples

          # Loop over all WDExample directories
          for wdexample_dir in WDExample*; do
            # Change to the WDExample directory
            cd "$wdexample_dir/B1/V0/BZ"

            # Loop over all files in the WDExample directory
            for file in *; do
              # If the file does not end with .mx1 or .xml (case insensitive), then remove it
              if [[ ! $file =~ \.(mx1|xml)$ ]]; then
                rm "$file"
              fi
            done

            # Go back to the Examples directory before the next iteration
            cd - > /dev/null
            cd - > /dev/null
          done

      - name: Commit and push if it changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatisches Loeschen von Example Daten"
          git push
